version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: mq-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: mq-redis
    ports:
      - "6379:6379"